### ISSUE TITLE
Assertion failure in Bitvector::readBit

### ISSUE THREAD

**Issue by KlimentSerafimov** [efficient/SuRF#14]
assert(pos <= num_bits_) in Bitvector::readBit fails. I'll attach the dataset, workload, and setup shortly.

**Comment by KlimentSerafimov** [comment]
Running this testing code fails the assert mentioned above on the attached dataset and workload.
The assert gets triggered after creation and evaluation of multiple instances of SuRF with different parameter values.
My guess is that there is some global state or variable that maintains it's value from the previous instance without being reset.

[workload.txt](https://github.com/efficient/SuRF/files/8189833/workload.txt)
[dataset.txt](https://github.com/efficient/SuRF/files/8189834/dataset.txt)

`#include <iostream>
#include <vector>

#include "include/surf.hpp"
#include <string>

#include <fstream>

using namespace surf;
using namespace std;

vector<string> read_dataset(const string& file_path) {
    vector<string> dataset;
    ifstream file(file_path);
    cout << "INIT reading dataset file " << file_path << endl;
    int id = 0;
    while (!file.eof()) {
        string line;
        getline(file, line);
        if(!line.empty()) {
            dataset.push_back(line);
        }
        id++;
    }
    file.close();
    cout << "END reading dataset file " << file_path << endl;
    cout << "READ " << dataset.size() << " rows" << endl;
    return dataset;
}

static vector<string> split(string str, const string& delim) {
    vector<string> ret;
    while (str.find(delim) != std::string::npos) {
        if (str.find(delim) >= 1) {
            ret.push_back(str.substr(0, str.find(delim)));
        }
        str = str.substr(str.find(delim) + delim.size(), str.size() - (str.find(delim) + delim.size()));
    }
    if (!str.empty()) {
        ret.push_back(str);
    }
    return ret;
}

vector<pair<string, string> > read_workload(const string& file_path) {
    vector<pair<string, string> > workload;

    ifstream file(file_path);

    cout << "INIT reading workload file " << file_path << endl;
    int id = 0;
    while (!file.eof()) {
        string line;
        getline(file, line);
        assert(line.find(' ') != std::string::npos);
        if (!line.empty()) {
            vector<string> parts = split(line, " ");
            assert(parts.size() == 2);
            workload.emplace_back(parts[0], parts[1]);
        }
        id++;
    }
    file.close();
    cout << "END reading workload file " << file_path << endl;
    cout << "READ " << workload.size() << " rows" << endl;
    return workload;
}

int surf_main() {
    vector<string> dataset = read_dataset("dataset.txt");
    vector<pair<string, string> > workload = read_workload("workload.txt");
    for (int trie_size = 0; trie_size <= 64; trie_size++) {
        surf::SuRF *surf_real = new surf::SuRF(dataset, surf::kReal, 0, trie_size);
        for (int i = 0; i < workload.size(); i++) {
            bool out = surf_real->lookupRange(workload[i].first, true, workload[i].second, true);
            cout << out << endl;
        }
    }
    return 0;
}
`

**Comment by huanchenz** [comment]
Please check out the latest commit which hopefully fixes the bug :)

**Comment by KlimentSerafimov** [comment]
Hi! The new commit did indeed fix the issue above.
HOWEVER!
There is another issue. Same exact setup, only with the following dataset and workload:
[dataset.txt](https://github.com/efficient/SuRF/files/8230142/dataset.txt)
[workload.txt](https://github.com/efficient/SuRF/files/8230164/workload.txt)

Fails at the exact same assert, but probably for a different reason (it's not because of initialization of multiple instances of surf). 
Failure happens even with this surf_main:

    int surf_main() {
        vector<string> dataset = read_dataset("dataset.txt");
        sort(dataset.begin(), dataset.end());
        vector<pair<string, string> > workload = read_workload("workload.txt");
        int trie_size = 45; {
            surf::SuRF *surf_real = new surf::SuRF(dataset, surf::kReal, 0, trie_size);
            int i = 0; {
                bool out = surf_real->lookupRange(workload[i].first, true, workload[i].second, true);
                cout << out << endl;
            }
        }
        assert(false);
        return 0;
    }

**Comment by huanchenz** [comment]
Committed with additional fixes.

**Comment by KlimentSerafimov** [comment]
Thanks! It works now!
