### ISSUE TITLE
deSerialize(serialize()) doesn't clone properly.

### ISSUE THREAD

**Issue by KlimentSerafimov** [efficient/SuRF#15]
Trying to use deSerialize(serialize())  as a cloning function, but it doesn't work properly.
In the following code, I use deSerialize(serialize()) to make a copy of an instance, and then destroy the copy immediately, which crashes the program with a "double free or corruption (out); Signal: SIGABRT (Aborted)" error.

    #include <iostream>
    #include <vector>
    
    #include "include/surf.hpp"
    
    using namespace surf;
    #include <iostream>
    #include <vector>
    #include <algorithm>
    
    #include "include/surf.hpp"
    #include <string>
    
    #include <fstream>
    
    using namespace surf;
    using namespace std;
    
    vector<string> read_dataset(const string& file_path) {
        vector<string> dataset;
        ifstream file(file_path);
        cout << "INIT reading dataset file " << file_path << endl;
        int id = 0;
        while (!file.eof()) {
            string line;
            getline(file, line);
            if(!line.empty()) {
                dataset.push_back(line);
            }
            id++;
        }
        file.close();
        cout << "END reading dataset file " << file_path << endl;
        cout << "READ " << dataset.size() << " rows" << endl;
        return dataset;
    }
    
    static vector<string> split(string str, const string& delim) {
        vector<string> ret;
        while (str.find(delim) != std::string::npos) {
            if (str.find(delim) >= 1) {
                ret.push_back(str.substr(0, str.find(delim)));
            }
            str = str.substr(str.find(delim) + delim.size(), str.size() - (str.find(delim) + delim.size()));
        }
        if (!str.empty()) {
            ret.push_back(str);
        }
        return ret;
    }
    
    vector<pair<string, string> > read_workload(const string& file_path) {
        vector<pair<string, string> > workload;
    
        ifstream file(file_path);
    
        cout << "INIT reading workload file " << file_path << endl;
        int id = 0;
        while (!file.eof()) {
            string line;
            getline(file, line);
            assert(line.find(' ') != std::string::npos);
            if (!line.empty()) {
                vector<string> parts = split(line, " ");
                assert(parts.size() == 2);
                workload.emplace_back(parts[0], parts[1]);
            }
            id++;
        }
        file.close();
        cout << "END reading workload file " << file_path << endl;
        cout << "READ " << workload.size() << " rows" << endl;
        return workload;
    }
    
    int surf_main() {
        vector<string> dataset = read_dataset("dataset.txt");
        sort(dataset.begin(), dataset.end());
        vector<pair<string, string> > workload = read_workload("workload.txt");
        surf::SuRF *surf_real = new surf::SuRF(dataset, surf::kReal, 0, 8);
        surf::SuRF::deSerialize(surf_real->serialize())->destroy();
        assert(false);
        return 0;
    }

**Comment by huanchenz** [comment]
Committed a fix for this issue :)
