### ISSUE TITLE
How can the lookUpRange function be parallel?

### ISSUE THREAD

**Issue by lzyLuke** [efficient/SuRF#5]
Hi, I come here again...

Here, the most important feature range query :
https://github.com/efficient/SuRF/blob/e038235b4bf2985960d57d34d83bcd06446e1665/include/surf.hpp#L215

And in the bench, there is a multi-thread work load test
https://github.com/efficient/SuRF/blob/e038235b4bf2985960d57d34d83bcd06446e1665/bench/workload_multi_thread.cpp#L28

This lookUpRange function uses a private class variable **iter_**. It first calls **iter_.clear()**, which clear some variables, but do not new them. When multi-threads call this function, they will all modify this variable at the same time which could nullify the programming logic.
Perhaps it should new a iter every time when there is a call?

Thanks!

**Comment by huanchenz** [comment]
Yes, you are right. Thanks! To execute lookupRange in parallel, you need separate iterators (we didn't run the multi-threaded range query experiment in our paper). We embed a default iterator in the SuRF class for single-thread performance.
