### ISSUE TITLE
Buffer overrun in bitvector

### ISSUE THREAD

**Issue by chenfucn** [efficient/SuRF#8]
I saw a previous issue has been closed, citing assertions at the beginning of the functions. But those assertions are NOT sufficient.

Description of the problem:
potential buffer overrun in line 95 and 96 of bitvector.hpp
https://github.com/efficient/SuRF/blob/cbf235840133e4828f8a98b24a71f4f049c644c2/include/bitvector.hpp#L95

The assertion at beginning of the function (assert(pos <= num_bits_);)  does NOT work, suppose there's a run of 0s longer than 128 near the end of the bit vector, when we enter the function the pos might as well within range, but the logic in the function will keep reading the next long until it runs over the buffer by exactly 8 bytes.  The function will returns the wrong result because of this.

**Comment by huanchenz** [comment]
Again, thanks! Looks like the while statement above this line should be:
while (word_id < numWords() - 1) {

**Comment by chenfucn** [comment]
Usually a for loop would be safer and easier to reason about.
