### ISSUE TITLE
Potential assertion failure in louds sparse

### ISSUE THREAD

**Issue by chenfucn** [efficient/SuRF#9]
https://github.com/efficient/SuRF/blob/cbf235840133e4828f8a98b24a71f4f049c644c2/include/louds_sparse.hpp#L246

At the line referenced above, suppose we are at the very last node, whose label is legitimately '0xff', then readBit(pos + 1) would trigger assertion failure.

**Comment by huanchenz** [comment]
Hey, thanks a lot for pointing this out. Seems like if I change the line to
&& louds_bits_->readBit(pos)) { 
it would work.
What do you think?

**Comment by chenfucn** [comment]
If I understand correctly, this is to judge whether 'pos' is the last label in a node. In that case what you propose does not work. I would suggest write another function  

inline bool isEndOfNode(pos)  { return pos == lastPosition || louds_bits_readBit(pos + 1); }

this way not only your code is more readable, you avoid code clone

**Comment by huanchenz** [comment]
Thanks! I'll push a fix soon.
